<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Mercato.Application/Mercato.Application.csproj" />
    <ProjectReference Include="../Mercato.Infrastructure/Mercato.Infrastructure.csproj" />
    <ProjectReference Include="../Mercato.Domain/Mercato.Domain.csproj" />
  </ItemGroup>
</Project>
