<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Nop.Plugin.Mercato.Connector</AssemblyName>
    <NopCommerceVersion>4.90.7</NopCommerceVersion>
    <OutputPath Condition="'$(NopCommerceRoot)' != ''">$(NopCommerceRoot)/src/Presentation/Nop.Web/Plugins/Mercato.Connector</OutputPath>
    <OutDir Condition="'$(NopCommerceRoot)' != ''">$(OutputPath)</OutDir>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="plugin.json" />
    <None Remove="Views/Configure.cshtml" />
    <None Remove="Views/_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views/Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views/_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Mercato.NopCommerce.Core/Mercato.NopCommerce.Core.csproj" />
    <ProjectReference Include="$(NopCommerceRoot)/src/Presentation/Nop.Web/Nop.Web.csproj" Condition="'$(NopCommerceRoot)' != ''" />
    <ClearPluginAssemblies Include="$(NopCommerceRoot)/src/Build/ClearPluginAssemblies.proj" Condition="'$(NopCommerceRoot)' != ''" />
  </ItemGroup>

  <ItemGroup Condition="'$(NopCommerceRoot)' == ''">
    <Compile Remove="NopPlugin.cs" />
    <Compile Remove="NopStartup.cs" />
    <Compile Remove="MercatoConnectorSettings.cs" />
    <Compile Remove="NopMercatoConfiguration.cs" />
    <Compile Remove="MercatoConnectorConfigurationModel.cs" />
    <Compile Remove="MercatoConnectorController.cs" />
  </ItemGroup>

  <Target Name="NopTarget" AfterTargets="Build" Condition="'$(NopCommerceRoot)' != ''">
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(OutDir)" Targets="NopClear" />
  </Target>

</Project>
